// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/nikitades/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UrlRepository is an autogenerated mock type for the UrlRepository type
type UrlRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, original, short, createdAt
func (_m *UrlRepository) Create(ctx context.Context, original string, short string, createdAt time.Time) (domain.Url, error) {
	ret := _m.Called(ctx, original, short, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (domain.Url, error)); ok {
		return rf(ctx, original, short, createdAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) domain.Url); ok {
		r0 = rf(ctx, original, short, createdAt)
	} else {
		r0 = ret.Get(0).(domain.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, original, short, createdAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOriginal provides a mock function with given fields: ctx, original
func (_m *UrlRepository) FindByOriginal(ctx context.Context, original string) (domain.Url, error) {
	ret := _m.Called(ctx, original)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 domain.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Url, error)); ok {
		return rf(ctx, original)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Url); ok {
		r0 = rf(ctx, original)
	} else {
		r0 = ret.Get(0).(domain.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, original)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByShort provides a mock function with given fields: ctx, short
func (_m *UrlRepository) FindByShort(ctx context.Context, short string) (domain.Url, error) {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for FindByShort")
	}

	var r0 domain.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Url, error)); ok {
		return rf(ctx, short)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Url); ok {
		r0 = rf(ctx, short)
	} else {
		r0 = ret.Get(0).(domain.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlRepository creates a new instance of UrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepository {
	mock := &UrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
