// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UrlGenerator is an autogenerated mock type for the UrlGenerator type
type UrlGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: l
func (_m *UrlGenerator) Generate(l int) string {
	ret := _m.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(l)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewUrlGenerator creates a new instance of UrlGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlGenerator {
	mock := &UrlGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
